server:
  port: '8124'
  # 生产环境部署时的配置
  host: '0.0.0.0'  # 允许外部访问
  cors_origins: 
    - 'http://localhost:3000'
    - 'http://localhost:8080'
    - 'http://localhost:8124'
    - 'https://redamancy.com.cn'
    - 'http://redamancy.com.cn'
  
  # 服务器配置
  read_timeout: 30s
  write_timeout: 30s
  max_header_bytes: 1048576  # 1MB

database:
  driver: 'sqlite3'
  dsn: './star-cloud.db'
  
  # 数据库连接池配置
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: '5m'
  conn_max_idle_time: '3m'

jwt:
  secret: 'your-secret-key'
  access_token_ttl: '15m'
  refresh_token_ttl: '168h'  # 7天

# 上传配置
upload:
  max_file_size: 20971520      # 20MB
  max_video_size: 52428800     # 50MB
  max_concurrent_uploads: 10
  max_upload_rate: 5242880     # 5MB/s (生产环境)
  
  # 文件类型限制
  allowed_types:
    - 'image/*'
    - 'video/*'
    - 'audio/*'
    - 'application/pdf'
    - 'application/msword'
    - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    - 'text/plain'
    - 'text/markdown'

# 日志配置
logging:
  level: 'info'  # debug, info, warn, error
  format: 'json'  # json, text
  output: 'stdout'  # stdout, file
  file_path: './logs/app.log'
  max_size: 100  # MB
  max_age: 30    # 天
  max_backups: 10

# 安全配置
security:
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst_size: 20
  
  cors:
    allow_credentials: true
    allow_headers:
      - 'Origin'
      - 'Content-Type'
      - 'Authorization'
      - 'User-UUID'
  
  # 密码策略
  password:
    min_length: 6
    require_special: false

# 生产环境部署配置
deployment:
  type: 'prod'  # baota, local, prod
  domain: 'redamancy.com.cn'
  static_path: '/srv/apps/axi-star-cloud/front'
  upload_path: '/srv/apps/axi-star-cloud/uploads'

# 缓存配置
cache:
  type: 'memory'  # memory, redis
  redis:
    addr: 'localhost:6379'
    password: ''
    db: 0
  memory:
    max_size: 1000
    ttl: '1h'

# 异步任务配置
async:
  worker_size: 5
  queue_size: 100
  max_retries: 3
  retry_delay: '5s'

# 热重载配置
hot_reload:
  enabled: false  # 生产环境关闭热重载
  check_interval: '5s'
  backup_on_change: true

# 优雅关闭配置
graceful_shutdown:
  timeout: '30s'
  wait_for_connections: true 