version: '3.8'

services:
  axi-star-cloud:
    build: .
    container_name: axi-star-cloud
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./front/uploads:/root/front/uploads
      - ./backend/config:/root/config
    environment:
      - GIN_MODE=release
    networks:
      - axi-star-network

networks:
  axi-star-network:
    driver: bridge 